"""PreToolUse guard: keep agents from hand-editing files that must be generated.

README §3 forbids fabricated metrics, and the gold sets are the answer keys those
metrics are scored against. An agent that "fixes" a failing benchmark by editing
`reports/` or a gold label has produced exactly the number the project promises
never to publish, so those edits are refused outright, with the command that
should have been run instead.

A second tier is legitimate but deserves a human look: policy fixtures with a
strict format and a deliberate trap, merged migrations, CI gates, and the
evaluation threshold ratchet. Those ask rather than refuse.

Reads the hook payload on stdin; standard library only.
"""

from __future__ import annotations

import json
import os
import sys
from fnmatch import fnmatch
from pathlib import Path

DENY: tuple[tuple[str, str], ...] = (
    (
        "reports/*",
        "reports/ is regenerated evidence. Run the producing command (/regenerate-reports).",
    ),
    (
        "data/*_gold.jsonl",
        "Gold sets are hand-labelled answer keys. If a label is wrong, stop and ask the user.",
    ),
    (
        "data/manifest.csv",
        "Generated by `uv run rxauth-build-dataset`; hand edits risk split leakage.",
    ),
    ("data/ingestion_manifest.csv", "Generated by `uv run rxauth-build-dataset`."),
    ("data/documents/*", "Generated corpus. Regenerate with `uv run rxauth-build-dataset`."),
    ("data/rendered/*", "Generated corpus. Regenerate with `uv run rxauth-build-dataset`."),
    ("data/reviewer_feedback.jsonl", "Runtime reviewer feedback store; never edited by hand."),
    ("artifacts/*", "Build output. Retrain with `uv run rxauth-train-classifier`."),
    ("uv.lock", "Change dependencies with `uv add` / `uv lock`, not by editing the lockfile."),
    (
        "web/package-lock.json",
        "Change dependencies with `npm install` in web/, not by editing the lockfile.",
    ),
    (".venv/*", "Managed by uv."),
    ("web/node_modules/*", "Managed by npm."),
)

ASK: tuple[tuple[str, str], ...] = (
    (
        "data/policies/*",
        "Policy fixtures have a strict format, and PA-207 is a deliberate retrieval trap.",
    ),
    ("alembic/versions/*", "Editing a merged migration rewrites history. Prefer a new revision."),
    (".github/workflows/*", "CI gates protect report reproducibility and tenant isolation."),
    (
        "src/rxauth_ai/evaluation_suite.py",
        "Thresholds are a ratchet. Lowering one needs an explicit reason.",
    ),
)


def _relative(file_path: str, root: Path) -> str | None:
    try:
        rel = Path(file_path).resolve().relative_to(root.resolve())
    except (ValueError, OSError):
        return None
    return rel.as_posix().lower() if os.name == "nt" else rel.as_posix()


def _decide(decision: str, reason: str) -> None:
    json.dump(
        {
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": decision,
                "permissionDecisionReason": reason,
            }
        },
        sys.stdout,
    )


def main() -> int:
    payload = json.load(sys.stdin)
    tool_input = payload.get("tool_input") or {}
    file_path = tool_input.get("file_path") or tool_input.get("notebook_path")
    if not file_path:
        return 0
    root = Path(os.environ.get("CLAUDE_PROJECT_DIR") or payload.get("cwd") or ".")
    rel = _relative(file_path, root)
    if rel is None:
        return 0

    for pattern, reason in DENY:
        if fnmatch(rel, pattern):
            _decide("deny", f"{rel}: {reason}")
            return 0
    for pattern, reason in ASK:
        if fnmatch(rel, pattern):
            if pattern == "alembic/versions/*" and not Path(file_path).exists():
                continue
            _decide("ask", f"{rel}: {reason}")
            return 0
    return 0


if __name__ == "__main__":
    sys.exit(main())
