"""initial case run and reviewer feedback schema

Revision ID: 270b221cb65e
Revises:
Create Date: 2026-09-02 11:04:27.495266
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "270b221cb65e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "case_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payer", sa.String(length=255), nullable=False),
        sa.Column("medication", sa.String(length=255), nullable=False),
        sa.Column("indication", sa.String(length=255), nullable=False),
        sa.Column("policy_id", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.Column("workflow_version", sa.String(length=64), nullable=False),
        sa.Column("matcher_version", sa.String(length=64), nullable=False),
        sa.Column("extractor_version", sa.String(length=64), nullable=True),
        sa.Column("generator_version", sa.String(length=64), nullable=True),
        sa.Column("criteria_total", sa.Integer(), nullable=False),
        sa.Column("criteria_satisfied", sa.Integer(), nullable=False),
        sa.Column("criteria_not_satisfied", sa.Integer(), nullable=False),
        sa.Column("criteria_missing", sa.Integer(), nullable=False),
        sa.Column("criteria_needs_review", sa.Integer(), nullable=False),
        sa.Column("groundedness_gate", sa.String(length=16), nullable=False),
        sa.Column("draft_gate", sa.String(length=16), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_case_runs_case_created", "case_runs", ["case_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_case_runs_case_id"), "case_runs", ["case_id"], unique=False)
    op.create_index(op.f("ix_case_runs_request_id"), "case_runs", ["request_id"], unique=False)
    op.create_table(
        "reviewer_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("criterion_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("reviewer_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("recorded_at", sa.String(length=64), nullable=False),
        sa.Column("original_result", sa.String(length=32), nullable=False),
        sa.Column("corrected_result", sa.String(length=32), nullable=True),
        sa.Column("matcher_version", sa.String(length=64), nullable=False),
        sa.Column("generator_version", sa.String(length=64), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_reviewer_decisions_action"), "reviewer_decisions", ["action"], unique=False
    )
    op.create_index(
        "ix_reviewer_decisions_case_criterion",
        "reviewer_decisions",
        ["case_id", "criterion_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reviewer_decisions_case_id"), "reviewer_decisions", ["case_id"], unique=False
    )
    op.create_index(
        op.f("ix_reviewer_decisions_matcher_version"),
        "reviewer_decisions",
        ["matcher_version"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reviewer_decisions_reviewer_id"),
        "reviewer_decisions",
        ["reviewer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_reviewer_decisions_run_id"), "reviewer_decisions", ["run_id"], unique=False
    )
    op.create_table(
        "case_documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("document_id", sa.String(length=64), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("document_type", sa.String(length=64), nullable=False),
        sa.Column("classification_confidence", sa.Float(), nullable=False),
        sa.Column("requires_review", sa.Boolean(), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["case_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "document_id", name="uq_run_document"),
    )
    op.create_index(op.f("ix_case_documents_run_id"), "case_documents", ["run_id"], unique=False)
    op.create_table(
        "criterion_evaluations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("criterion_id", sa.String(length=64), nullable=False),
        sa.Column("result", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("evaluation_method", sa.String(length=32), nullable=False),
        sa.Column("matcher_version", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["case_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "criterion_id", name="uq_run_criterion"),
    )
    op.create_index(
        op.f("ix_criterion_evaluations_result"), "criterion_evaluations", ["result"], unique=False
    )
    op.create_index(
        op.f("ix_criterion_evaluations_run_id"), "criterion_evaluations", ["run_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_criterion_evaluations_run_id"), table_name="criterion_evaluations")
    op.drop_index(op.f("ix_criterion_evaluations_result"), table_name="criterion_evaluations")
    op.drop_table("criterion_evaluations")
    op.drop_index(op.f("ix_case_documents_run_id"), table_name="case_documents")
    op.drop_table("case_documents")
    op.drop_index(op.f("ix_reviewer_decisions_run_id"), table_name="reviewer_decisions")
    op.drop_index(op.f("ix_reviewer_decisions_reviewer_id"), table_name="reviewer_decisions")
    op.drop_index(op.f("ix_reviewer_decisions_matcher_version"), table_name="reviewer_decisions")
    op.drop_index(op.f("ix_reviewer_decisions_case_id"), table_name="reviewer_decisions")
    op.drop_index("ix_reviewer_decisions_case_criterion", table_name="reviewer_decisions")
    op.drop_index(op.f("ix_reviewer_decisions_action"), table_name="reviewer_decisions")
    op.drop_table("reviewer_decisions")
    op.drop_index(op.f("ix_case_runs_request_id"), table_name="case_runs")
    op.drop_index(op.f("ix_case_runs_case_id"), table_name="case_runs")
    op.drop_index("ix_case_runs_case_created", table_name="case_runs")
    op.drop_table("case_runs")
    # ### end Alembic commands ###
